In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame({"col1":[1,2,3], "col2":[2,3,4]})

In [6]:
df

col1  col2
0     1     2
1     2     3
2     3     4

In [7]:
a = df.to_numpy()

In [8]:
a

array([[1, 2],
       [2, 3],
       [3, 4]])

In [19]:
np.array([a[:, 0], a[:,1]]).T

array([[1, 2],
       [2, 3],
       [3, 4]])

In [8]:
def yeet(arr1, arr2):
    return 2

In [9]:
def get_correl_matrix(arr : np.ndarray, method ,column_name_list: list = None, is_symetric: bool = False) -> pd.DataFrame:
    shape = arr.shape
    cols = shape[1]
    result = np.ones(shape=(cols,cols))

    if is_symetric:
        return pd.DataFrame(arr).corr(method=method)

    if method == "transfer_entropy":
        method = get_transfer_entropy

    for i in range(shape[1]):
        for j in range(shape[1]):
            if i == j:
                continue
            arr1 = arr[:,j]
            arr2 = arr[:,i]
            result[i,j] = method(arr[i], arr[j])
    
    if column_name_list is not None:
        result = pd.DataFrame(data=result, columns=column_name_list, index=column_name_list)
        
    return result

In [10]:
get_correl_matrix(df.to_numpy(), "dfj", column_name_list=["col1", "col2"])

TypeError: 'str' object is not callable

In [2]:
import numpy as np
l = np.array([(1,2), (1,3), (1,4), (1,5), (1,6)])

for i, (j,k) in enumerate(l):
    print(i, j, k)

0 1 2
1 1 3
2 1 4
3 1 5
4 1 6


In [7]:
for i, j in l:
    print(i,j)

1 2
1 3
1 4
1 5
1 6


In [31]:
rows = 500
cols = 4
a = np.array([[i]*rows for i in range(cols)])
df = pd.DataFrame(columns=[f"col{i}" for i in range(cols)], data=a.T)
df["timestamp"] = pd.date_range("2018-01-01", periods=rows, freq="h")
df.set_index(keys=["timestamp"], inplace=True)
df

col0  col1  col2  col3
timestamp                                  
2018-01-01 00:00:00     0     1     2     3
2018-01-01 01:00:00     0     1     2     3
2018-01-01 02:00:00     0     1     2     3
2018-01-01 03:00:00     0     1     2     3
2018-01-01 04:00:00     0     1     2     3
...                   ...   ...   ...   ...
2018-01-21 15:00:00     0     1     2     3
2018-01-21 16:00:00     0     1     2     3
2018-01-21 17:00:00     0     1     2     3
2018-01-21 18:00:00     0     1     2     3
2018-01-21 19:00:00     0     1     2     3

[500 rows x 4 columns]

In [1]:
import numpy as np
import pandas as pd
a = [[1,2], [3,4], [5,6]]
df = pd.DataFrame(data=a, columns=["col1", "col2"])

In [2]:
df

col1  col2
0     1     2
1     3     4
2     5     6

In [6]:
df.median()

col1    3.0
col2    4.0
dtype: float64

In [3]:
df.mean(axis=0)

col1    3.0
col2    4.0
dtype: float64

In [4]:
df.sub(df.mean(axis=0))

col1  col2
0  -2.0  -2.0
1   0.0   0.0
2   2.0   2.0

In [5]:
l = [1,3,2]
n = len(l)
l[1:n]

[3, 2]

In [7]:
# mn = floor(n**(1/3-0.01))
# mnSpacings = xs[mn:] - xs[:-mn] #Python starts from zero

mn = 3
mnSpacings = [1,2,3,4,5,6,6]

print(mnSpacings[3:])
print(mnSpacings[:-3])




[4, 5, 6, 6]
[1, 2, 3, 4]


In [8]:
def renamer (name):
    return name + "t"
df.rename(columns = renamer, inplace=True)

In [29]:
def add_hlc(input_df):
    input_df["mean"] = input_df[["col1t", "col2t"]].mean(axis=1)


In [30]:
add_hlc(df)

In [31]:
df

col1t  col2t  col1  mean
0      1      2     1   1.5
1      3      4     2   3.5
2      5      6     3   5.5

In [25]:
df[["col1t", "col2t"]].mean(axis=1).values

array([1.5, 3.5, 5.5])

In [34]:
from DataManagement.data_manager import DataManager
data_manager = DataManager()

In [35]:
data_manager.add_noise_to_df(df)

In [36]:
df

col1t     col2t      col1      mean
0  0.983947  1.994224  0.998498  1.492545
1  2.985520  3.984470  1.983328  3.495071
2  4.988072  6.029091  3.001879  5.492577