In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame({"col1":[1,2,3], "col2":[2,3,4]})

In [6]:
df

col1  col2
0     1     2
1     2     3
2     3     4

In [7]:
a = df.to_numpy()

In [8]:
a

array([[1, 2],
       [2, 3],
       [3, 4]])

In [19]:
np.array([a[:, 0], a[:,1]]).T

array([[1, 2],
       [2, 3],
       [3, 4]])

In [8]:
def yeet(arr1, arr2):
    return 2

In [9]:
def get_correl_matrix(arr : np.ndarray, method ,column_name_list: list = None, is_symetric: bool = False) -> pd.DataFrame:
    shape = arr.shape
    cols = shape[1]
    result = np.ones(shape=(cols,cols))

    if is_symetric:
        return pd.DataFrame(arr).corr(method=method)

    if method == "transfer_entropy":
        method = get_transfer_entropy

    for i in range(shape[1]):
        for j in range(shape[1]):
            if i == j:
                continue
            arr1 = arr[:,j]
            arr2 = arr[:,i]
            result[i,j] = method(arr[i], arr[j])
    
    if column_name_list is not None:
        result = pd.DataFrame(data=result, columns=column_name_list, index=column_name_list)
        
    return result

In [10]:
get_correl_matrix(df.to_numpy(), "dfj", column_name_list=["col1", "col2"])

TypeError: 'str' object is not callable

In [2]:
import numpy as np
l = np.array([(1,2), (1,3), (1,4), (1,5), (1,6)])

for i, (j,k) in enumerate(l):
    print(i, j, k)

0 1 2
1 1 3
2 1 4
3 1 5
4 1 6


In [7]:
for i, j in l:
    print(i,j)

1 2
1 3
1 4
1 5
1 6


In [31]:
rows = 500
cols = 4
a = np.array([[i]*rows for i in range(cols)])
df = pd.DataFrame(columns=[f"col{i}" for i in range(cols)], data=a.T)
df["timestamp"] = pd.date_range("2018-01-01", periods=rows, freq="h")
df.set_index(keys=["timestamp"], inplace=True)
df

col0  col1  col2  col3
timestamp                                  
2018-01-01 00:00:00     0     1     2     3
2018-01-01 01:00:00     0     1     2     3
2018-01-01 02:00:00     0     1     2     3
2018-01-01 03:00:00     0     1     2     3
2018-01-01 04:00:00     0     1     2     3
...                   ...   ...   ...   ...
2018-01-21 15:00:00     0     1     2     3
2018-01-21 16:00:00     0     1     2     3
2018-01-21 17:00:00     0     1     2     3
2018-01-21 18:00:00     0     1     2     3
2018-01-21 19:00:00     0     1     2     3

[500 rows x 4 columns]

In [5]:
import numpy as np
a = np.array([[1,2], [3,4], [5,6]])
np.flip(a, axis=0)

array([[2, 1],
       [4, 3],
       [6, 5]])